src/api/urls.py
from django.urls import path, include
from django.conf.urls import url

from core.hooks import UrlHook

api_urls = UrlHook()

app_name = 'api'

urlpatterns = [
    path('', include(api_urls.get())),
]

src/resource_hub/core/urls.py
import django.contrib.auth.views as dj_auth
from django.urls import include, path, re_path
from django.views.i18n import JavaScriptCatalog
from resource_hub.api.urls import api_urls
from resource_hub.control.urls import control_urls
from resource_hub.core.views import api, auth, control, site

from .hooks import UrlHook

finance_urls = UrlHook()
finance_urls.register([
    path('bank-accounts/', control.FinanceBankAccounts.as_view(),
         name='finance_bank_accounts'),
    path('payment-methods/manage/',
         control.FinancePaymentMethodsManage.as_view(), name='finance_payment_methods_manage'),
    path('payment-methods/manage/<int:pk>/', control.FinancePaymentMethodsEdit.as_view(
    ), name='finance_payment_methods_edit'),
    path('payment-methods/add/<str:scope>/',
         control.FinancePaymentMethodsAdd.as_view(), name='finance_payment_methods_add'),
    path('contracts/credited/', control.FinanceContractsCredited.as_view(),
         name='finance_contracts_credited'),
    path('contracts/debited/', control.FinanceContractsDebited.as_view(),
         name='finance_contracts_debited'),
    path('contracts/manage/<int:pk>/', control.FinanceContractsManageDetails.as_view(),
         name='finance_contracts_manage_details'),
    path('contracts/<int:pk>/messages/', control.FinanceContractsMessages.as_view(),
         name='finance_contracts_messages'),
    path('contract-procedures/manage/', control.FinanceContractProceduresManage.as_view(),
         name='finance_contract_procedures_manage'),
    path('contract-procedures/create/', control.FinanceContractProceduresCreate.as_view(),
         name='finance_contract_procedures_create'),
    path('invoices/outgoing/', control.FinanceInvoicesOutgoing.as_view(),
         name='finance_invoices_outgoing'),
    path('invoices/incoming/', control.FinanceInvoicesIncoming.as_view(),
         name='finance_invoices_incoming'),
])
control_urls.register([
    # account
    path('', control.Home.as_view(), name='home'),
    path('account/settings/<str:scope>/',
         control.AccountSettings.as_view(),
         name='account_settings'),
    path('account/security/<str:scope>/',
         control.AccountSecurity.as_view(),
         name='account_security'),
    path('account/notifications/settings/',
         control.NotificationsSettings.as_view(),
         name='notifications_settings'),
    path('account/verification/resend', auth.VerificationResend.as_view(),
         name='account_verification_resend'),

    # notifications
    path('notifications/', control.Notifications.as_view(), name='notifications'),

    # finance
    path('finance/', include(finance_urls.get())),

    # organizations
    path('organizations/manage/',
         control.OrganizationsManage.as_view(),
         name='organizations_manage'),
    path('organizations/create/',
         control.OrganizationsCreate.as_view(),
         name='organizations_create'),
    path('organizations/manage/<int:organization_id>/profile/edit/<str:scope>/',
         control.OrganizationsProfileEdit.as_view(),
         name='organizations_profile_edit'),
    path('organizations/manage/<int:organization_id>/members/',
         control.OrganizationsMembers.as_view(),
         name='organizations_members'),
    path('organizations/manage/<int:organization_id>/members/add/',
         control.OrganizationsMembersAdd.as_view(),
         name='organizations_members_add'),
    path('organizations/manage/<int:organization_id>/profile/',
         control.OrganizationsProfile.as_view(),
         name='organizations_profile'),

    # locations
    path('locations/manage/', control.LocationsManage.as_view(),
         name='locations_manage'),
    path('locations/create/', control.LocationsCreate.as_view(),
         name='locations_create'),
    path('locations/manage/<int:pk>/', control.LocationsEdit.as_view(),
         name='locations_edit'),
])

api_urls.register([
    path('users/search/', api.UserSearch.as_view(), name='search_users'),
    path('actors/list', api.ActorList.as_view(), name='actor_list'),
    path('actors/change',
         api.ActorChange.as_view(), name='actor_change'),
    path('organizations/<int:organization_pk>/members/change', api.OrganizationMembersChange.as_view(),
         name='organizations_members_change'),
    path('locations/search/', api.Locations.as_view(),
         name='locations_search'),
    path('contracts/list', api.ContractsList.as_view(), name='contracts_list'),
    path('notifications/list', api.NotificationsList.as_view(),
         name='notifications_list'),
    path('notifications/unread', api.NotificationsUnread.as_view(),
         name='notifications_unread'),
    path('notifications/mark/read/', api.NotificationsMarkRead.as_view(),
         name='notifications_mark_read'),
])

app_name = 'core'
urlpatterns = [
    # site
    path('', site.index, name='index'),
    path('home/', site.Home.as_view(), name='home'),
    path('bug/', site.ReportBug.as_view(), name='report_bug'),
    path('language/', site.Language.as_view(), name='language'),
    path('terms/', site.Terms.as_view(), name='terms'),
    path('imprint/', site.Imprint.as_view(), name='imprint'),
    path('privacy/', site.DataPrivacyStatement.as_view(), name='privacy'),
    path('locations/<slug:slug>/',
         site.LocationsProfile.as_view(), name='locations_profile'),
    path('actor/<slug:slug>/',
         site.ActorProfile.as_view(),
         name='actor_profile'),

    # path
    path('register/', auth.Register.as_view(), name='register'),
    path('login/', auth.custom_login, name='login'),
    path('logout/', dj_auth.LogoutView.as_view(
        template_name='core/logout.html'), name='logout'),
    re_path(r'^verify/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
            auth.Verify.as_view(), name='verify'),
    path('password/reset/', dj_auth.PasswordResetView.as_view(
        template_name='core/password_reset.html', success_url='/password/reset/done/', email_template_name='core/mail_password_reset.html'), name='password_reset'),
    path('password/reset/done/', dj_auth.PasswordResetDoneView.as_view(
        template_name='core/password_reset_done.html', ), name='password_reset_done'),
    re_path(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$', dj_auth.PasswordResetConfirmView.as_view(
        template_name='core/password_reset_confirm.html', success_url='/password/reset/complete/'), name='password_reset_confirm'),
    path('password/reset/complete/', dj_auth.PasswordResetCompleteView.as_view(
        template_name='core/password_reset_complete.html')),
    path('actor/set', auth.SetRole.as_view(), name='actor_set'),


    # locale stuff
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n.js', JavaScriptCatalog.as_view(
        packages=['recurrence']), name='jsi18n'),
]

src/resource_hub/items/urls.py
from django.urls import path

from resource_hub.core.urls import api_urls, control_urls

from . import api, views

app_name = 'items'

api_urls.register([
    path('items/', api.Items.as_view(), name='items'),
    path('items/<int:pk>/bookings/', api.Bookings.as_view(), name='item_bookings'),
    path('items/<slug:owner_slug>/<slug:item_slug>/feed.ics',
         api.ICSFeed(), name='items_ics_feed'),
])

control_urls.register([
    path('items/manage/', views.ItemsManage.as_view(), name='items_manage'),
    path('items/manage/<int:pk>/',
         views.ItemsEdit.as_view(), name='items_edit'),
    path('items/create/', views.ItemsCreate.as_view(), name='items_create'),
    path('items/contract-procedures/create', views.ContractProceduresCreate.as_view(),
         name='items_contract_procedures_create'),
    path('items/contract-procedures/edit/<int:pk>/', views.ContractProceduresEdit.as_view(),
         name='items_contract_procedures_edit'),
    path('items/bookings/credited', views.ItemBookingsCredited.as_view(),
         name='item_bookings_credited'),
    path('items/bookings/debited', views.ItemBookingsDebited.as_view(),
         name='item_bookings_debited'),
])

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:owner_slug>/<slug:item_slug>/',
         views.ItemsDetails.as_view(), name='details'),
    path('<slug:owner_slug>/<slug:item_slug>/book',
         views.ItemBookingsCreate.as_view(), name='book'),
    path('bookings/<int:pk>/', views.ItemBookings.as_view(),
         name='bookings'),
]

src/resource_hub/urls.py
"""
resource_hub URL Configuration

"""
import importlib

from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

for app in apps.get_app_configs():
    if importlib.util.find_spec(app.name + '.urls'):
        importlib.import_module(app.name + '.urls')

urlpatterns = [
    # apps
    path('', include('resource_hub.core.urls')),
    path('api/', include('resource_hub.api.urls')),
    path('control/', include('resource_hub.control.urls')),
    path('venues/', include('resource_hub.venues.urls')),
    path('items/', include('resource_hub.items.urls')),
    path('workshops/', include('resource_hub.workshops.urls')),

    # external apps
    path('admin/', admin.site.urls),
    path('django-rq/', include('django_rq.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

src/resource_hub/venues/urls.py
from django.urls import path

from resource_hub.core.urls import api_urls, control_urls
from resource_hub.venues import api, views

app_name = 'venues'

api_urls.register([
    path('venues/', api.Venues.as_view(), name='venues'),
    path('venues/<int:pk>/events/',
         api.VenueEvents.as_view(), name='venues_event_feed'),
])

control_urls.register([
    path('venues/manage/', views.VenuesManage.as_view(), name='venues_manage'),
    path('venues/manage/<int:pk>/',
         views.VenuesEdit.as_view(), name='venues_edit'),
    path('venues/create/', views.VenuesCreate.as_view(), name='venues_create'),
    path('venues/contract-procedures/create', views.ContractProceduresCreate.as_view(),
         name='venues_contract_procedures_create'),
    path('venues/contract-procedures/edit/<int:pk>/', views.ContractProceduresEdit.as_view(),
         name='venues_contract_procedures_edit'),
])

urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:location_slug>/<slug:venue_slug>',
         views.VenuesDetails.as_view(), name='venue_details'),
    path('<slug:location_slug>/<slug:venue_slug>/events/create/',
         views.EventsCreate.as_view(), name='events_create'),

]

src/resource_hub/venues/templates/venues/_contract_overview.html
{% load i18n %}

{% with event=contract.event %}
<h2>{% trans 'Event details' %}</h2>
<div class="ui stackable two column grid">
    <div class="column">
        <div class="ui list">
            <div class="item">
                <div class="header">{% trans 'Name' %}</div>
                {{ event.name }}
            </div>
            <div class="item">
                <div class="header">{% trans 'Category' %}</div>
                {{ event.category.name }}
            </div>
            <div class="item">
                <div class="header">{% trans 'Tags' %}</div>
                {% for tag in event.tags.all %}
                {{ tag }}
                {% endfor %}
            </div>
            <div class="item">
                <div class="header">{% trans 'Description' %}</div>
                {{ event.description|safe }}
            </div>
        </div>
    </div>
    {% if contract.event.thumbnail_original %}
    <div class="column">
        <img src="{{ contract.event.thumbnail.url }}" alt="{% trans 'Venue thumbnail' %}">
    </div>
    {% endif %}
</div>
{% endwith %}

src/resource_hub/venues/templates/venues/_room_feed.html
{% load i18n %}

<div id="feed-loader" class="ui active centered inline loader"></div>
<div id="room-feed" class="ui stackable three column cards grid"></div>

<script id="room-item-template" type="text/template">
    <div class="column">
        <a id='card' class="ui fluid card" href="%room_link%">
            <div class="content">
                <img class="ui avatar image" src="%owner_thumbnail%"> %owner_name%
            </div>
            <div class="blurring dimmable image">
                <div class="ui dimmer">
                    <div class="content">
                        <div class="center">
                            <div class="ui inverted button">{% trans 'Details' %}</div>
                        </div>
                    </div>
                </div>
                <img class="thumbnail" src="%room_thumbnail%">
            </div>
            <div class="ui placeholder">
                <div class="square image"></div>
            </div>
            <div class="content">
                <div class="header">%name%</div>
                <div class="meta">
                    <p><i class="location arrow icon"></i> %location_name%</p>
                    <p><i class="map marker alternate icon"></i> %address_string%</p>
                </div>
            </div>
        </a>
    </div>
</script>

<script>
    function create_feed(name = null, id = null) {
        var template = document.getElementById("room-item-template");
        var templateHtml = template.innerHTML;
        var params = [];
        var query = "";

        if (name !== null) {
            params.push('name=' + name);
        }

        if (id !== null) {
            params.push('id=' + id);
        }

        if (params.length > 0) {
            query = "?" + params[0];
            for (var i = 1; i < params.length; i++) {
                query += "&" + params[i];
            }
        }

        $.ajax({
            'url': "{% url 'api:venues' %}" + query,
            'type': 'GET',
            'dataType': 'JSON'
        }).done(function (data) {
            var feed = "";

            $.each(data, function (i, room) {
                feed += templateHtml
                    .replace(/%room_link%/g, room['room_link'])
                    .replace(/%owner_name%/g, room.owner['name'])
                    .replace(/%owner_thumbnail%/g, room.owner['thumbnail'])
                    .replace(/%room_thumbnail%/g, room['thumbnail'])
                    .replace(/%name%/g, room['name'])
                    .replace(/%location_name%/g, room.location.name)
                    .replace(/%address_string%/g, room.location.address['address_string']);
            });

            remove_loader('#feed-loader');
            $('#room-feed').html(feed);
            $('.thumbnail').on('load', function () {
                $('.placeholder').hide();
            });
            $('.fluid.card .image').dimmer({ on: 'hover' });
        });

    }
</script>

src/resource_hub/venues/templates/venues/_venue_feed.html
{% load i18n %}
{% load sekizai_tags %}

{% include 'venues/_venue_feed_renderer.html' %}
{% addtoblock 'js' %}
<script>
    $(document).ready(function () {
        var venue_feed = new BlockFeed("{% url 'api:venues' %}", 'venue-feed', render_venue_feed);
        venue_feed.create_feed();

        $('#filter-form').on('submit', function (e) {
            e.preventDefault();
            var name = $(this).find("input[name='search_query']").val();
            venue_feed.create_feed({ name: name });
        });
    });
</script>
{% endaddtoblock %}

src/resource_hub/venues/templates/venues/_venue_feed_renderer.html
{% load i18n %}
{% load sekizai_tags %}

{% include '_block_feed.html' with blocks='three' feed_id='venue-feed' %}
{% addtoblock 'js' %}
<script id="venue-item-template" type="text/template">
    <div class="column">
        <a id='card' class="ui fluid card" href="%venue_link%">
            <div class="content">
                <img class="ui avatar image" src="%owner_thumbnail%" alt="{% trans 'Logo' %}"> %owner_name%
            </div>
            <div class="blurring dimmable image">
                <div class="ui dimmer">
                    <div class="content">
                        <div class="center">
                            <div class="ui inverted button">{% trans 'Details' %}</div>
                        </div>
                    </div>
                </div>
                <img class="thumbnail" src="%venue_thumbnail%" alt="{% trans 'Thumbnail' %}">
            </div>
            <div class="ui placeholder">
                <div class="square image"></div>
            </div>
            <div class="content">
                <div class="header">%name%</div>
                <div class="meta">
                    <p><i class="location arrow icon"></i> %location_name%</p>
                    <p><i class="map marker alternate icon"></i> %address_string%</p>
                </div>
            </div>
        </a>
    </div>
</script>
<script>
    function render_venue_feed(data) {
        var template = document.getElementById("venue-item-template");
        var templateHtml = template.innerHTML;
        var feed = '';
        $.each(data, function (i, venue) {
            feed += templateHtml
                .replace(/%venue_link%/g, venue['venue_link'])
                .replace(/%owner_name%/g, venue.owner['name'])
                .replace(/%owner_thumbnail%/g, venue.owner['thumbnail'])
                .replace(/%venue_thumbnail%/g, venue['thumbnail'])
                .replace(/%name%/g, venue['name'])
                .replace(/%location_name%/g, venue.location.name)
                .replace(/%address_string%/g, venue.location.address['address_string']);
        });
        return feed;
    }
</script>
{% endaddtoblock %}

src/resource_hub/venues/templates/venues/_venue_info.html
{% load i18n %}

<div class="ui stackable two column grid">
    <div class="column">
        <div class="ui list">
            {% if venue.bookable %}
            <div class="header">
                {% trans 'Base price' %}
            </div>
            {{ venue.base_price }}
            {% endif %}
        </div>
    </div>
    <div class="column">
        <div class="ui list">
        </div>
    </div>
    <!-- <div class="header">{% trans 'Description' %}</div> -->
    <div>
        <div class="header">
            {% trans 'Description' %}
        </div>
        {{ venue.description|safe }}
    </div>
</div>

src/resource_hub/venues/templates/venues/location_profile.html
{% load i18n %}
{% load sekizai_tags %}

<div class="ui horizontal section divider">{% trans 'Venues' %}</div>

{% include 'venues/_venue_feed_renderer.html' %}
{% addtoblock 'js' %}
<script>
    $(document).ready(function () {
        var venue_feed = new BlockFeed('{% url "api:venues" %}', 'venue-feed', render_venue_feed);
        venue_feed.create_feed({ id: '{{ location.id }}' });
    });
</script>
{% endaddtoblock %}

src/resource_hub/venues/templates/venues/room_details.html
{% extends 'core/__base.html' %}
{% load i18n %}
{% load static %}

{% block extra_head %}
<link href="{% static 'fullcalendar/main.min.css' %}" rel="stylesheet">
<link href="{% static 'fullcalendar/daygrid/main.min.css' %}" rel="stylesheet">
<script src="{% static 'fullcalendar/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/daygrid/main.min.js' %}"></script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var calendarEl = document.getElementById('calendar');

        var calendar = new FullCalendar.Calendar(calendarEl, {
            events: "{% url 'api:venues_event_feed' room_id=room.id %}",
            plugins: ['dayGrid']
        });

        calendar.render();
    });
</script>
{% endblock %}

{% block content %}
<div class="ui stackable two column grid">
    <div class="column">
        <h1>{{ room.name }}</h1>
        <p>
            {{ room.description |safe }}
        </p>
    </div>
    <div class="column">
        {% if room.bookable %}
        <div id='calendar'></div>
        <div class="spacer">
            <a class="ui right labeled positive icon button" href="{% url 'venues:events_create' room_id=room.id %}">
                {% trans 'book' %}
                <i class="calendar alternate outline icon"></i>
            </a>
        </div>
        {% else %}
        <img class="ui fluid image" src="{{ room.thumbnail_original.url }}">
        {% endif %}
    </div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

src/resource_hub/venues/templates/venues/room_events_create.html
{% extends 'core/__base.html' %}
{% load i18n %}

{% block content %}
<h1>
    {% trans 'create event' %}
</h1>
<form class="ui form" method="POST" enctype="multipart/form-data">
    {% include '_form.html' with form=event_form %}
    {% include 'core/_identity.html' with actor=actor %}
    <button class="ui positive right labeled icon button" type="submit">
        {% trans 'create event' %}
        <i class="calendar plus outline icon"></i>
    </button>
</form>
{% endblock %}

{% block scripts %}
<script src="{% url 'core:jsi18n' %}"></script>
{{ event_form.media }}
{% endblock %}

src/resource_hub/venues/templates/venues/venue_details.html
{% extends 'core/__base.html' %}
{% load i18n %}

{% block not_in_container %}
<div class="container">
    <div class="location-image" style="background-image: url('{{ venue.thumbnail_original.url }}')">
    </div>
</div>
<div class="main container large">
    <div class="ui stackable two column grid">
        <div class="eight wide column">
            <nav class="button-navigation">
                {% if venue.bookable %}
                <a class="ui right labeled positive icon button"
                    href="{% url 'venues:events_create' venue_slug=venue.slug location_slug=venue.location.slug %}">
                    {% trans 'Book' %}
                    <i class="calendar alternate outline icon"></i>
                </a>
                {% endif %}
                <a class="ui labeled right floated icon back button" href="{% url 'items:index' %}">
                    <i class="left arrow icon"></i>
                    {% trans 'Back' %}
                </a>
            </nav>
            <h1>{{ venue.name }}</h1>
            {% include 'venues/_venue_info.html' with venue=venue %}
        </div>
        <div class="eight wide column">
            {% include 'core/_location_info.html' with location=venue.location %}
        </div>
    </div>
    <div class="section-container">
        {% if equipment_gallery %}
        <h2>{% trans 'Equipment & Services' %}</h2>
        {% include '_gallery.html' with gallery=equipment_gallery %}
        {% endif %}
    </div>
    <div class="section-container">
        {% if venue.gallery.images.all %}
        <h2>{% trans 'Gallery' %}</h2>
        {% include '_gallery.html' with gallery=venue.gallery.images.all %}
        {% endif %}
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function () {
        $('.fluid.card .image').dimmer({ on: 'hover' });
    })
</script>
{% endblock %}

src/resource_hub/venues/templates/venues/venue_events_create.html
{% extends 'core/__base.html' %}
{% load i18n %}
{% load static %}
{% load custom_tags %}

{% block extra_head %}
<script src="{% url 'core:jsi18n' %}"></script>
{{ event_form.media }}
{% endblock %}

{% block not_in_container %}
<div class="main container large">
    <div class="ui stackable two column grid">
        <div class="seven wide column">
            {% setvar 'Y-m-d H:i' as format %}
            {% url 'api:venues_event_feed' pk=venue.pk as event_url %}
            {% get_current_language as lang %}
            {% include '_calendar.html' with event_url=event_url lang=lang ics_url=ics_url format=format %}
        </div>
        <div class="nine wide column">
            {% url 'venues:venue_details' venue_slug=venue.slug location_slug=venue.location.slug as url %}
            {% include '_back_button.html' with url=url %}
            <h1>
                {% trans 'Create event' %}
            </h1>

            <form class="ui form" method="POST" enctype="multipart/form-data">
                {% include '_form.html' with form=venue_contract_form %}
                <div id="container">
                    {% include '_form.html' with form=event_form %}
                </div>
                {% include 'core/_identity.html' with actor=actor %}
                <button class="ui positive right labeled icon button" type="submit">
                    {% trans 'Check event' %}
                    <i class="zoom-in icon"></i>
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}



{% block scripts %}
<script src="{% static 'datetimepicker/build/jquery.datetimepicker.full.min.js' %}"></script>
<script>
    function setEnd(currentDateTime) {
        end.datetimepicker({
            minDate: currentDateTime,
            defaultTime: currentDateTime,
            defaultDate: currentDateTime
        })
    }

    var locale = "{% get_current_language as LANG %}{{ LANG }}";
    jQuery.datetimepicker.setLocale(locale);
    var start = $('#id_dtstart').datetimepicker({
        onChangeDateTime: setEnd,
        step: 30,
        format: 'Y-m-d H:i',
        mask: true

    });
    var end = $('#id_dtend').datetimepicker({
        step: 30,
        format: 'Y-m-d H:i',
        mask: true,
    });
</script>
<script>
    $(document).ready(function () {
        const targetNode = document.getElementById('container');

        const config = { attributes: false, childList: true, subtree: true };

        const callback = function (mutationsList, observer) {
            for (let mutation of mutationsList) {
                if (mutation.type === 'childList') {
                    for (let node of mutation.addedNodes) {
                        $(node).find('input[name="limit"]').prop('checked', true);
                        $(node).find('.until-count').removeClass('disabled');
                        $(node).find('input[name="until_count"]').prop('disabled', false);
                        $(node).find('.date-field').prop('disabled', false);

                        var date_limit = $(node).find('input[class="date-field"]');
                        var count_limmit = $(node).find('input[name="count"]');
                        $(node).find('li[class="until"]').find('input[name="until_count"]').on('click', function () {
                            date_limit.prop('required', true).removeClass('disabled');
                            count_limmit.prop('required', false).addClass('disabled');
                        });
                        $(node).find('li[class="count"]').find('input[name="until_count"]').on('click', function () {
                            date_limit.prop('required', false).addClass('disabled');
                            count_limmit.prop('required', true).removeClass('disabled');
                        });
                    }
                }
            }
        };

        const observer = new MutationObserver(callback);
        observer.observe(targetNode, config);
    });
</script>
{% endblock %}