src/api/urls.py
from django.urls import path, include
from django.conf.urls import url

from core.hooks import UrlHook

api_urls = UrlHook()

app_name = 'api'

urlpatterns = [
    path('', include(api_urls.get())),
]

src/core/admin/urls.py
from django.urls import path, include
from django.conf.urls import url

from core.hooks import UrlHook


app_name = 'admin'

admin_urls = UrlHook()
urlpatterns = [
    path('', include(admin_urls.get())),
]

src/resource_hub/control/urls.py
from django.conf.urls import url
from django.urls import include, path

from resource_hub.core.hooks import UrlHook

app_name = 'control'

control_urls = UrlHook()
urlpatterns = [
    path('', include(control_urls.get())),
]

src/resource_hub/core/urls.py
import django.contrib.auth.views as dj_auth
from django.urls import include, path, re_path
from django.views.i18n import JavaScriptCatalog
from resource_hub.api.urls import api_urls
from resource_hub.control.urls import control_urls
from resource_hub.core.views import api, auth, control, site

from .hooks import UrlHook

finance_urls = UrlHook()
finance_urls.register([
    path('bank-accounts/', control.FinanceBankAccounts.as_view(),
         name='finance_bank_accounts'),
    path('payment-methods/manage/',
         control.FinancePaymentMethodsManage.as_view(), name='finance_payment_methods_manage'),
    path('payment-methods/manage/<int:pk>/', control.FinancePaymentMethodsEdit.as_view(
    ), name='finance_payment_methods_edit'),
    path('payment-methods/add/<str:scope>/',
         control.FinancePaymentMethodsAdd.as_view(), name='finance_payment_methods_add'),
    path('contracts/credited/', control.FinanceContractsCredited.as_view(),
         name='finance_contracts_credited'),
    path('contracts/debited/', control.FinanceContractsDebited.as_view(),
         name='finance_contracts_debited'),
    path('contracts/manage/<int:pk>/', control.FinanceContractsManageDetails.as_view(),
         name='finance_contracts_manage_details'),
    path('contracts/<int:pk>/messages/', control.FinanceContractsMessages.as_view(),
         name='finance_contracts_messages'),
    path('contract-procedures/manage/', control.FinanceContractProceduresManage.as_view(),
         name='finance_contract_procedures_manage'),
    path('contract-procedures/create/', control.FinanceContractProceduresCreate.as_view(),
         name='finance_contract_procedures_create'),
    path('invoices/outgoing/', control.FinanceInvoicesOutgoing.as_view(),
         name='finance_invoices_outgoing'),
    path('invoices/incoming/', control.FinanceInvoicesIncoming.as_view(),
         name='finance_invoices_incoming'),
])
control_urls.register([
    # account
    path('', control.Home.as_view(), name='home'),
    path('account/settings/<str:scope>/',
         control.AccountSettings.as_view(),
         name='account_settings'),
    path('account/security/<str:scope>/',
         control.AccountSecurity.as_view(),
         name='account_security'),
    path('account/notifications/settings/',
         control.NotificationsSettings.as_view(),
         name='notifications_settings'),
    path('account/verification/resend', auth.VerificationResend.as_view(),
         name='account_verification_resend'),

    # notifications
    path('notifications/', control.Notifications.as_view(), name='notifications'),

    # finance
    path('finance/', include(finance_urls.get())),

    # organizations
    path('organizations/manage/',
         control.OrganizationsManage.as_view(),
         name='organizations_manage'),
    path('organizations/create/',
         control.OrganizationsCreate.as_view(),
         name='organizations_create'),
    path('organizations/manage/<int:organization_id>/profile/edit/<str:scope>/',
         control.OrganizationsProfileEdit.as_view(),
         name='organizations_profile_edit'),
    path('organizations/manage/<int:organization_id>/members/',
         control.OrganizationsMembers.as_view(),
         name='organizations_members'),
    path('organizations/manage/<int:organization_id>/members/add/',
         control.OrganizationsMembersAdd.as_view(),
         name='organizations_members_add'),
    path('organizations/manage/<int:organization_id>/profile/',
         control.OrganizationsProfile.as_view(),
         name='organizations_profile'),

    # locations
    path('locations/manage/', control.LocationsManage.as_view(),
         name='locations_manage'),
    path('locations/create/', control.LocationsCreate.as_view(),
         name='locations_create'),
    path('locations/manage/<int:pk>/', control.LocationsEdit.as_view(),
         name='locations_edit'),
])

api_urls.register([
    path('users/search/', api.UserSearch.as_view(), name='search_users'),
    path('actors/list', api.ActorList.as_view(), name='actor_list'),
    path('actors/change',
         api.ActorChange.as_view(), name='actor_change'),
    path('organizations/<int:organization_pk>/members/change', api.OrganizationMembersChange.as_view(),
         name='organizations_members_change'),
    path('locations/search/', api.Locations.as_view(),
         name='locations_search'),
    path('contracts/list', api.ContractsList.as_view(), name='contracts_list'),
    path('notifications/list', api.NotificationsList.as_view(),
         name='notifications_list'),
    path('notifications/unread', api.NotificationsUnread.as_view(),
         name='notifications_unread'),
    path('notifications/mark/read/', api.NotificationsMarkRead.as_view(),
         name='notifications_mark_read'),
])

app_name = 'core'
urlpatterns = [
    # site
    path('', site.index, name='index'),
    path('home/', site.Home.as_view(), name='home'),
    path('bug/', site.ReportBug.as_view(), name='report_bug'),
    path('language/', site.Language.as_view(), name='language'),
    path('terms/', site.Terms.as_view(), name='terms'),
    path('imprint/', site.Imprint.as_view(), name='imprint'),
    path('privacy/', site.DataPrivacyStatement.as_view(), name='privacy'),
    path('locations/<slug:slug>/',
         site.LocationsProfile.as_view(), name='locations_profile'),
    path('actor/<slug:slug>/',
         site.ActorProfile.as_view(),
         name='actor_profile'),

    # path
    path('register/', auth.Register.as_view(), name='register'),
    path('login/', auth.custom_login, name='login'),
    path('logout/', dj_auth.LogoutView.as_view(
        template_name='core/logout.html'), name='logout'),
    re_path(r'^verify/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
            auth.Verify.as_view(), name='verify'),
    path('password/reset/', dj_auth.PasswordResetView.as_view(
        template_name='core/password_reset.html', success_url='/password/reset/done/', email_template_name='core/mail_password_reset.html'), name='password_reset'),
    path('password/reset/done/', dj_auth.PasswordResetDoneView.as_view(
        template_name='core/password_reset_done.html', ), name='password_reset_done'),
    re_path(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$', dj_auth.PasswordResetConfirmView.as_view(
        template_name='core/password_reset_confirm.html', success_url='/password/reset/complete/'), name='password_reset_confirm'),
    path('password/reset/complete/', dj_auth.PasswordResetCompleteView.as_view(
        template_name='core/password_reset_complete.html')),
    path('actor/set', auth.SetRole.as_view(), name='actor_set'),


    # locale stuff
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n.js', JavaScriptCatalog.as_view(
        packages=['recurrence']), name='jsi18n'),
]

src/resource_hub/urls.py
"""
resource_hub URL Configuration

"""
import importlib

from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

for app in apps.get_app_configs():
    if importlib.util.find_spec(app.name + '.urls'):
        importlib.import_module(app.name + '.urls')

urlpatterns = [
    # apps
    path('', include('resource_hub.core.urls')),
    path('api/', include('resource_hub.api.urls')),
    path('control/', include('resource_hub.control.urls')),
    path('venues/', include('resource_hub.venues.urls')),
    path('items/', include('resource_hub.items.urls')),
    path('workshops/', include('resource_hub.workshops.urls')),

    # external apps
    path('admin/', admin.site.urls),
    path('django-rq/', include('django_rq.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

src/resource_hub/core/models/base.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from django_countries.fields import CountryField
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from model_utils.fields import MonitorField
from model_utils.managers import InheritanceManager

from ..managers import CombinedManager
from ..utils import get_valid_slug


class BaseModel(models.Model):
    # fields
    is_deleted = models.BooleanField(
        default=False,
        verbose_name=_('Deleted?'),
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Created at'),
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_('Updated at'),
    )
    objects = CombinedManager()
    all_objects = InheritanceManager()

    class Meta:
        abstract = True

    # methods
    def soft_delete(self):
        self.is_deleted = True
        self.save()

    def get_subclass(self):
        return self.__class__.objects.get_subclass(pk=self.pk)


class BaseStateMachine(BaseModel):
    class STATE:
        PENDING = 'p'

    STATES = [
        (STATE.PENDING, _('pending')),
    ]
    STATE_GRAPH = None

    state = models.CharField(
        max_length=2,
        default=STATE.PENDING,
        verbose_name=_('State'),
    )
    state_changed = MonitorField(
        monitor='state',
        verbose_name=_('State changed at'),
    )

    def get_state_display(self):
        for state in self.STATES:
            if state[0] == self.state:
                return state[1]

    # state setters
    def move_to(self, state):
        if self.state in self.STATE_GRAPH and state in self.STATE_GRAPH[self.state]:
            self.state = state
        else:
            raise ValueError('Cannot move from state {} to state {}'.format(
                self.get_state_display(), state))

    class Meta:
        abstract = True


class Address(BaseModel):
    """
    describe address
    """

    # Fields
    street = models.CharField(
        max_length=50,
        null=True,
        blank=False,
        verbose_name=_('Street'),
    )
    street_number = models.CharField(
        max_length=10,
        null=True,
        blank=False,
        verbose_name=_('Street number'),
    )
    postal_code = models.CharField(
        max_length=5,
        null=True,
        blank=False,
        verbose_name=_('Postal code'),
    )
    city = models.CharField(
        max_length=128,
        null=True,
        blank=False,
        verbose_name=_('City'),
    )
    country = CountryField(
        null=True,
        blank=True,
        default=settings.DEFAULT_COUNTRY,
        verbose_name=_('Country'),
    )
    updated_by = models.ForeignKey(
        'User',
        null=True,
        related_name='address_updated_by',
        on_delete=models.SET_NULL,
    )

    # Metadata
    class Meta:
        ordering = ['postal_code', 'street']

    # Methods
    def __str__(self):
        return '{} {}, {} {}'.format(
            self.street,
            self.street_number,
            self.postal_code,
            self.city
        )


class BankAccount(BaseModel):
    """
    describes a bank account
    """

    # Fields
    account_holder = models.CharField(
        max_length=128,
        null=True,
        blank=True,
        verbose_name=_('Account holder'),
    )
    iban = models.CharField(
        max_length=40,
        null=True,
        blank=True,
        verbose_name=_('IBAN'),
    )
    bic = models.CharField(
        max_length=11,
        null=True,
        blank=True,
        verbose_name=_('BIC'),
    )
    updated_by = models.ForeignKey(
        'User',
        null=True,
        related_name='bank_account_updated_by',
        on_delete=models.SET_NULL,
    )

    # Metadata

    class Meta:
        ordering = ['bic', 'iban', ]

    # Methods
    def __str__(self):
        return '{} with account {} at {}'.format(
            self.account_holder,
            self.iban,
            self.bic
        )


class Location(BaseModel):
    """
    describing locations
    """

    # Fields
    slug = models.SlugField(
        max_length=50,
        unique=True,
        db_index=True,
        verbose_name=_('Slug'),
    )
    address = models.ForeignKey(
        Address,
        on_delete=models.CASCADE,
        verbose_name=_('Address'),
    )
    name = models.CharField(
        max_length=128,
        null=True,
        blank=True,
        verbose_name=_('Name'),
    )
    description = models.TextField(
        null=True,
        blank=True,
        verbose_name=_('Description'),
    )
    latitude = models.DecimalField(
        max_digits=9,
        decimal_places=6,
        default=0,
        verbose_name=_('Latitude'),
    )
    longitude = models.DecimalField(
        max_digits=9,
        decimal_places=6,
        default=0,
        verbose_name=_('Longitude'),
    )
    image = models.ImageField(
        null=True,
        blank=True,
        upload_to='images/',
        default='images/default.png',
        verbose_name=_('Image'),
    )
    thumbnail = ImageSpecField(
        source='image',
        processors=[
            ResizeToFill(400, 300),
        ],
        format='PNG',
        options={
            'quality': 60,
        }
    )
    is_public = models.BooleanField(
        default=True,
        verbose_name=_('Public?'),
        help_text=_(
            'Display the location in feeds and display full information'),
    )
    is_editable = models.BooleanField(
        default=False,
        verbose_name=_('Editable?'),
        help_text=_(
            'Allow other users to link information to this location'),
    )
    owner = models.ForeignKey(
        'Actor',
        on_delete=models.CASCADE,
        verbose_name=_('Owner'),
    )

    # Metadata
    class Meta:
        ordering = ['name']

    # Methods
    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.pk:
            self.slug = get_valid_slug(self, self.name)

        super(Location, self).save(*args, **kwargs)


class Gallery(BaseModel):
    pass


class GalleryImage(BaseModel):
    gallery = models.ForeignKey(
        Gallery,
        on_delete=models.PROTECT,
        related_name='images',
        verbose_name=_('Gallery'),
    )
    caption = models.CharField(
        max_length=255,
        verbose_name=_('Caption'),
    )
    image = models.ImageField(
        null=False,
        upload_to='images/',
        verbose_name=_('Image'),
    )
    thumbnail = ImageSpecField(
        source='image',
        processors=[
            ResizeToFill(400, 400),
        ],
        format='JPEG',
        options={
            'quality': 90,
        }
    )

src/resource_hub/core/views/site.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views import View

from resource_hub.core.forms import ActorForm, ReportBugForm
from resource_hub.core.models import Actor, Location

from ..utils import get_site_info


def index(request):
    return redirect(reverse('core:home'))


class Home(View):
    def get(self, request):
        return render(request, 'core/home.html')


class Terms(View):
    def get(self, request):
        return render(request, 'core/terms_and_conditions.html', get_site_info())


class DataPrivacyStatement(View):
    def get(self, request):
        return render(request, 'core/data_privacy_statement.html', get_site_info())


class Imprint(View):
    def get(self, request):
        return render(request, 'core/imprint.html', get_site_info())


class ReportBug(View):
    template_name = 'core/report_bug.html'
    context = {
        'bug_form': ReportBugForm(),
    }

    def get(self, request):
        return render(request, self.template_name, self.context)

    def post(self, request):
        bug_form = ReportBugForm(request.POST)

        if bug_form.is_valid():
            bug_form.post()
            message = _('Your issue has been posted!')
            messages.add_message(request, messages.SUCCESS, message)

            return redirect(reverse('core:report_bug'))

        self.context['bug_form'] = bug_form
        return render(request, self.template_name, self.context)


class Language(View):
    def get(self, request):
        return render(request, 'core/language.html')


class ActorProfile(View):
    def get(self, request, slug):
        actor = get_object_or_404(Actor, slug=slug)
        context = {
            'actor': actor,
        }
        return render(request, 'core/actor_profile.html', context)


class LocationsProfile(View):
    def get(self, request, slug):
        location = get_object_or_404(Location, slug=slug)
        context = {
            'location': location
        }
        return render(request, 'core/locations_profile.html', context)

src/resource_hub/core/templates/core/control/_contract_feed.html
{% load i18n %}
{% load sekizai_tags %}

{% include '_block_feed.html' with blocks='three' %}

{% addtoblock 'js' %}
<script id="template" type="text/template">
    <div class="column">
        <a id='card' class="ui fluid card" href="%link%">
            <div class="ui %state% top attached label">%state_display%</div>
            <div class="content">
                <div class="header">%type_name%</div>
                <div class="meta">
                    <span class="date">{% trans 'created at' %} %created_at%</span>
                </div>
            </div>
        </a>
    </div>
</script>
<script>
    function render_contract_feed(data) {
        var template = document.getElementById("template");
        var templateHtml = template.innerHTML;
        var feed = "";

        $.each(data, function (i, contract) {
            feed += templateHtml
                .replace(/%type_name%/g, contract['type_name'])
                .replace(/%state%/g, contract['state'])
                .replace(/%state_display%/g, contract['state_display'])
                .replace(/%link%/g, contract['link'])
                .replace(/%created_at%/g, contract['created_at'])
                .replace(/%creditor_name%/g, contract.creditor['name'])
                .replace(/%creditor_thumbnail%/g, contract.creditor['thumbnail'])
        });
        return feed;
    }
    $(document).ready(function () {
        var contract_feed = new BlockFeed("{% url 'api:contracts_list' %}", 'feed', render_contract_feed);
        contract_feed.create_feed({ type: '{{ type }}' });
    });
</script>
{% endaddtoblock %}

src/resource_hub/core/templates/core/control/_location_form.html
{% load i18n %}
{% load sekizai_tags %}

<form class="ui form" method="POST" enctype="multipart/form-data">
    {% include '_form.html' with form=location_form %}
    {% include '_form.html' with form=address_form %}
    {% include 'core/_identity.html' with actor=actor %}
    <button class="ui positive right labeled icon button" type="submit">
        {{ action }}
        <i class="map marker alternate icon"></i>
    </button>
</form>

{% addtoblock 'js' %}
<script>
    $('.ui.search')
        .search({
            minCharacters: 5,
            apiSettings: {
                onResponse: function (result) {
                    return { results: result.features };
                },
                url: 'https://api.mapbox.com/geocoding/v5/mapbox.places/{query}.json?proximity=9.72492%2C52.3783212&types=address&access_token={{ MAP_API_TOKEN}}',

            },
            fields: {
                title: 'place_name',
                description: '',
                url: 'html_url'
            },

            onSelect: function (result, response) {
                var long = result.geometry.coordinates[0];
                var lat = result.geometry.coordinates[1];
                var street = result.text;
                var street_number = result.address;
                context = {}
                result.context.map(function (feature) {
                    name = feature.id.substr(0, feature.id.indexOf('.'));
                    if (feature.short_code) {
                        context[name] = feature.short_code.toUpperCase();
                    } else {
                        context[name] = feature.text
                    }
                });
                var postal_code = context.postcode || '';
                var city = context.place || '';
                var country = context.country || '';

                $('#id_longitude').val(long);
                $('#id_latitude').val(lat);
                $('#id_street').val(street);
                $('#id_street_number').val(street_number);
                $('#id_postal_code').val(postal_code);
                $('#id_city').val(city);
                $('#id_country').val(country);
            }
        })
        ; 
</script>
{% endaddtoblock %}

src/resource_hub/core/templates/core/control/finance_bank_accounts.html
{% extends "control/__base.html" %}
{% load i18n %}

{% block content %}
<h1>{% trans 'Add bank account' %}</h1>
{% include 'core/_identity.html' with actor=actor %}

{% endblock %}

src/resource_hub/core/templates/core/control/finance_contracts_messages.html
{% extends "control/__base.html" %}
{% load i18n %}


{% block admin_navigation %}
{% url 'control:finance_contracts_manage_details' pk=contract.pk as url %}
{% include '_back_button.html' with url=url %}
{% endblock %}

{% block content %}
<h1>{% trans 'Messages' %}</h1>
{% include 'core/control/_message_feed.html' with messages=contract.messages %}

<h2>{% trans 'Write message' %}</h2>
<form class="ui form" method="POST">
    {% include '_form.html' with form=contract_message_form %}
    <button type="submit" class="ui right labeled positive icon button">
        {% trans 'Send' %}
        <i class="ui paper plane icon"></i>
    </button>
</form>
{% endblock %}

src/resource_hub/core/templates/core/control/finance_payment_methods_edit.html
{% extends 'control/__base.html' %}
{% load i18n %}

{% block admin_navigation %}
{% url 'control:finance_payment_methods_manage' as url %}
{% include '_back_button.html' with url=url %}
{% endblock %}

{% block content %}
<h1>{% trans 'Edit bank transfer method' %}</h1>
<form class="ui form" method="POST">
    {% include '_form.html' with form=form %}
    <button class="ui positive right labeled icon button" type="sumit">
        {% trans 'Save' %}
        <i class="save icon"></i>
    </button>
</form>
{% endblock %}

src/resource_hub/core/templates/core/control/locations_edit.html
{% extends 'control/__base.html' %}
{% load i18n %}

{% block admin_navigation %}
{% url 'control:locations_manage' as url %}
{% include '_back_button.html' with url=url %}
{% endblock %}

{% block content %}
<h1>
    {% trans 'Edit location' %}
</h1>
<div class="section-container tab-content">
    {% trans 'Save' as action %}
    {% include 'core/control/_location_form.html' with action=action %}
</div>
{% endblock %}

src/resource_hub/core/templates/core/control/locations_profile_edit.html
{% extends 'control/__base.html' %}
{% load i18n %}

{% block admin-navigation %}
{% url 'control:locations_manage' as url %}
{% include '_back_button.html' with url=url %}
{% endblock %}

{% block content %}
<h1>
    {% trans 'edit profile' %}
</h1>
<div class="section-container tab-content">
    {% trans 'Save' as action %}
    {% include 'core/control/_location_form.html' with action=action %}
</div>
{% endblock %}

src/resource_hub/core/templates/core/control/notifications.html
{% extends 'control/__base.html' %}
{% load i18n %}
{% load sekizai_tags %}

{% block admin_navigation %}
<div id="mark_all_read" class="ui right floated icon button">
    <i class="check icon"></i>
    {% trans 'mark all read' %}
</div>
{% endblock %}

{% block content %}
<h1>{% trans 'Notifications' %}</h1>
{% include '_block_feed.html' with custom_class='ui feed' feed_id='notification-feed' %}

{% addtoblock 'js' %}
<script id="notification-template" type="text/template">
    <div class="event %is_read%" pk="%pk%">
        <div class="label" style="cursor: pointer;" onclick="show_notification('%link%', '%pk%');">
            <i class="%type% icon"></i>
        </div>
        <div class="content">
            <div class="summary" style="cursor: pointer;" onclick="show_notification('%link%', '%pk%');">
                <span>%header%</span>
                <div class="date">%created_at%</div>
            </div>
            <div>%message%</div>
            %attachments%
            <div class="meta">
                <a class="mark_read like %is_read%" pk="%pk%">
                    <i class="check icon"></i>
                    {% trans 'mark read' %}
                </a>
            </div>
        </div>
    </div>
</script>

<script id="attachment-wrapper-template" type="text/template">
<div class="ui list">
%items%
</div>

</script>
<script id="attachment-template" type="text/template">
<div class="item">
    <i class="file icon"></i>
    <div class="content">
        <a href="%path%">%filename%</a>
    </div>
</div>
</script>

<script>
    function show_notification(link, pk) {
        mark_read(pk, false, function () {
            window.location = link;
        })
    }
    function mark_read(pk, all = false, _callback = null) {
        var csrftoken = getCookie('csrftoken');
        var data = all ? "" : {
            pk: pk,
        }
        $.ajax({
            url: "{% url 'api:notifications_mark_read' %}",
            type: "PUT",
            dataType: "JSON",
            data: data,
            headers: { 'X-CSRFToken': csrftoken },
        }).done(function (data) {
            update_notification_indicator();
            button = all ? $('.mark_read') : $('a[pk=' + pk + ']');
            container = all ? $('.event') : $('div[pk=' + pk + ']');
            button.hide();
            container.removeClass('not_read');
            if (_callback) {
                return _callback()
            } else {
                return _callback
            }
        });
    }
    function render_notification_feed(data) {
        var notification_template = document.getElementById("notification-template").innerHTML;
        var attachment_template = document.getElementById("attachment-template").innerHTML;
        var attachment_wrapper_template = document.getElementById("attachment-wrapper-template").innerHTML;
        var feed = '';

        $.each(data, function (i, notification) {
            var read_flag = notification['is_read'] ? 'read' : 'not_read';
            var attachments = '';
            if (notification['attachments']) {
                var items = '';
                $.each(notification['attachments'], function (i, attachment) {
                    items += attachment_template
                        .replace(/%path%/g, attachment['path'])
                        .replace(/%filename%/g, attachment['filename']);
                });
                attachments = attachment_wrapper_template.replace(/%items%/g, items);
            }
            feed += notification_template
                .replace(/%pk%/g, notification['pk'])
                .replace(/%type%/g, notification['typ'])
                .replace(/%header%/g, notification['header'])
                .replace(/%message%/g, notification['message'])
                .replace(/%link%/g, notification['link'])
                .replace(/%is_read%/g, read_flag)
                .replace(/%attachments%/g, attachments)
                .replace(/%created_at%/g, notification['created_at']);
        });
        return feed;
    }
    function feed_listeners() {
        $('.mark_read').on('click', function () {
            var pk = $(this).attr('pk');
            mark_read(pk);
        });
    }
    $(document).ready(function () {
        var notification_feed = new BlockFeed("{% url 'api:notifications_list' %}", 'notification-feed', render_notification_feed);
        notification_feed.create_feed();

        $('#mark_all_read').on('click', function () {
            $(this).prop('disabled', true);
            mark_read(null, true);
        })
    });
</script>
{% endaddtoblock %}
{% endblock %}

src/resource_hub/core/templates/core/control/organizations_members.html
{% extends "control/__base.html" %}
{% load i18n %}
{% load django_tables2 %}

{% block admin_navigation %}
{% url 'control:organizations_profile' organization_id=organization.id as url %}
{% include '_back_button.html' with url=url %}
{% endblock %}

{% block content %}
{% url 'api:organizations_members_change' organization_pk=organization.pk as url %}
<div class="section-container tab-content">
    <h1>
        {{ organization.name }} {% trans 'members' %}
        <a class="ui labeled icon right floated green button"
            href="{% url 'control:organizations_members_add' organization_id=organization.id %}">
            <i class="plus icon"></i>
            {% trans 'add' %}
        </a>
    </h1>
    <div>
        {% if table %}
        {% render_table table %}
        {% include '_editable_table.html' with url=url %}
        {% else %}
        <p>
            {% trans 'no associated members found' %}
        </p>
        {% endif %}
    </div>
</div>
{% endblock %}

src/resource_hub/core/templates/core/control/organizations_members_add.html
{% extends "control/__base.html" %}
{% load i18n %}
{% load django_tables2 %}

{% block admin_navigation %}
{% url 'control:organizations_members' organization_id=organization.id as url %}
{% include '_back_button.html' with url=url %}
{% endblock %}

{% block content %}
<h1>
    {% blocktrans with organization=organization.name %}
    Invite person to {{ organization }}
    {% endblocktrans %}
</h1>
<div class="section-container tab-content">
    <form class="ui form" method="POST" action="">
        {% include "_form.html" with form=text_form %}
        <div class="field">
            <label>{% trans 'Invitations' %}</label>
            {% include "_formset.html" with formset=invitation_formset %}
        </div>
        <div class="section-container">
            <button class="ui positive right labeled icon button" type="submit">
                {% trans 'Invite' %}
                <i class="mail icon"></i>
            </button>
        </div>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script>
    $('.ui.search')
        .search({
            minCharacters: 2,
            apiSettings: {
                onResponse: function (result) {
                    return { results: Object.values(result) };
                },
                url: '{% url "api:search_users" %}?search={query}'
            },
            fields: {
                title: 'username',
                description: 'full_name',
                url: 'html_url'
            }
        })
        ; </script>
{% endblock %}