src/api/urls.py
from django.urls import path, include
from django.conf.urls import url

from core.hooks import UrlHook

api_urls = UrlHook()

app_name = 'api'

urlpatterns = [
    path('', include(api_urls.get())),
]

src/resource_hub/api/urls.py
from django.conf.urls import url
from django.urls import include, path

from resource_hub.core.hooks import UrlHook

app_name = 'api'
api_urls = UrlHook()
urlpatterns = [
    path('', include(api_urls.get())),
]

src/resource_hub/core/urls.py
import django.contrib.auth.views as dj_auth
from django.urls import include, path, re_path
from django.views.i18n import JavaScriptCatalog
from resource_hub.api.urls import api_urls
from resource_hub.control.urls import control_urls
from resource_hub.core.views import api, auth, control, site

from .hooks import UrlHook

finance_urls = UrlHook()
finance_urls.register([
    path('bank-accounts/', control.FinanceBankAccounts.as_view(),
         name='finance_bank_accounts'),
    path('payment-methods/manage/',
         control.FinancePaymentMethodsManage.as_view(), name='finance_payment_methods_manage'),
    path('payment-methods/manage/<int:pk>/', control.FinancePaymentMethodsEdit.as_view(
    ), name='finance_payment_methods_edit'),
    path('payment-methods/add/<str:scope>/',
         control.FinancePaymentMethodsAdd.as_view(), name='finance_payment_methods_add'),
    path('contracts/credited/', control.FinanceContractsCredited.as_view(),
         name='finance_contracts_credited'),
    path('contracts/debited/', control.FinanceContractsDebited.as_view(),
         name='finance_contracts_debited'),
    path('contracts/manage/<int:pk>/', control.FinanceContractsManageDetails.as_view(),
         name='finance_contracts_manage_details'),
    path('contracts/<int:pk>/messages/', control.FinanceContractsMessages.as_view(),
         name='finance_contracts_messages'),
    path('contract-procedures/manage/', control.FinanceContractProceduresManage.as_view(),
         name='finance_contract_procedures_manage'),
    path('contract-procedures/create/', control.FinanceContractProceduresCreate.as_view(),
         name='finance_contract_procedures_create'),
    path('invoices/outgoing/', control.FinanceInvoicesOutgoing.as_view(),
         name='finance_invoices_outgoing'),
    path('invoices/incoming/', control.FinanceInvoicesIncoming.as_view(),
         name='finance_invoices_incoming'),
])
control_urls.register([
    # account
    path('', control.Home.as_view(), name='home'),
    path('account/settings/<str:scope>/',
         control.AccountSettings.as_view(),
         name='account_settings'),
    path('account/security/<str:scope>/',
         control.AccountSecurity.as_view(),
         name='account_security'),
    path('account/notifications/settings/',
         control.NotificationsSettings.as_view(),
         name='notifications_settings'),
    path('account/verification/resend', auth.VerificationResend.as_view(),
         name='account_verification_resend'),

    # notifications
    path('notifications/', control.Notifications.as_view(), name='notifications'),

    # finance
    path('finance/', include(finance_urls.get())),

    # organizations
    path('organizations/manage/',
         control.OrganizationsManage.as_view(),
         name='organizations_manage'),
    path('organizations/create/',
         control.OrganizationsCreate.as_view(),
         name='organizations_create'),
    path('organizations/manage/<int:organization_id>/profile/edit/<str:scope>/',
         control.OrganizationsProfileEdit.as_view(),
         name='organizations_profile_edit'),
    path('organizations/manage/<int:organization_id>/members/',
         control.OrganizationsMembers.as_view(),
         name='organizations_members'),
    path('organizations/manage/<int:organization_id>/members/add/',
         control.OrganizationsMembersAdd.as_view(),
         name='organizations_members_add'),
    path('organizations/manage/<int:organization_id>/profile/',
         control.OrganizationsProfile.as_view(),
         name='organizations_profile'),

    # locations
    path('locations/manage/', control.LocationsManage.as_view(),
         name='locations_manage'),
    path('locations/create/', control.LocationsCreate.as_view(),
         name='locations_create'),
    path('locations/manage/<int:pk>/', control.LocationsEdit.as_view(),
         name='locations_edit'),
])

api_urls.register([
    path('users/search/', api.UserSearch.as_view(), name='search_users'),
    path('actors/list', api.ActorList.as_view(), name='actor_list'),
    path('actors/change',
         api.ActorChange.as_view(), name='actor_change'),
    path('organizations/<int:organization_pk>/members/change', api.OrganizationMembersChange.as_view(),
         name='organizations_members_change'),
    path('locations/search/', api.Locations.as_view(),
         name='locations_search'),
    path('contracts/list', api.ContractsList.as_view(), name='contracts_list'),
    path('notifications/list', api.NotificationsList.as_view(),
         name='notifications_list'),
    path('notifications/unread', api.NotificationsUnread.as_view(),
         name='notifications_unread'),
    path('notifications/mark/read/', api.NotificationsMarkRead.as_view(),
         name='notifications_mark_read'),
])

app_name = 'core'
urlpatterns = [
    # site
    path('', site.index, name='index'),
    path('home/', site.Home.as_view(), name='home'),
    path('bug/', site.ReportBug.as_view(), name='report_bug'),
    path('language/', site.Language.as_view(), name='language'),
    path('terms/', site.Terms.as_view(), name='terms'),
    path('imprint/', site.Imprint.as_view(), name='imprint'),
    path('privacy/', site.DataPrivacyStatement.as_view(), name='privacy'),
    path('locations/<slug:slug>/',
         site.LocationsProfile.as_view(), name='locations_profile'),
    path('actor/<slug:slug>/',
         site.ActorProfile.as_view(),
         name='actor_profile'),

    # path
    path('register/', auth.Register.as_view(), name='register'),
    path('login/', auth.custom_login, name='login'),
    path('logout/', dj_auth.LogoutView.as_view(
        template_name='core/logout.html'), name='logout'),
    re_path(r'^verify/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
            auth.Verify.as_view(), name='verify'),
    path('password/reset/', dj_auth.PasswordResetView.as_view(
        template_name='core/password_reset.html', success_url='/password/reset/done/', email_template_name='core/mail_password_reset.html'), name='password_reset'),
    path('password/reset/done/', dj_auth.PasswordResetDoneView.as_view(
        template_name='core/password_reset_done.html', ), name='password_reset_done'),
    re_path(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$', dj_auth.PasswordResetConfirmView.as_view(
        template_name='core/password_reset_confirm.html', success_url='/password/reset/complete/'), name='password_reset_confirm'),
    path('password/reset/complete/', dj_auth.PasswordResetCompleteView.as_view(
        template_name='core/password_reset_complete.html')),
    path('actor/set', auth.SetRole.as_view(), name='actor_set'),


    # locale stuff
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n.js', JavaScriptCatalog.as_view(
        packages=['recurrence']), name='jsi18n'),
]

src/resource_hub/urls.py
"""
resource_hub URL Configuration

"""
import importlib

from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

for app in apps.get_app_configs():
    if importlib.util.find_spec(app.name + '.urls'):
        importlib.import_module(app.name + '.urls')

urlpatterns = [
    # apps
    path('', include('resource_hub.core.urls')),
    path('api/', include('resource_hub.api.urls')),
    path('control/', include('resource_hub.control.urls')),
    path('venues/', include('resource_hub.venues.urls')),
    path('items/', include('resource_hub.items.urls')),
    path('workshops/', include('resource_hub.workshops.urls')),

    # external apps
    path('admin/', admin.site.urls),
    path('django-rq/', include('django_rq.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

src/resource_hub/workshops/models.py
import uuid
from datetime import datetime

from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.db.models import Q
from django.shortcuts import reverse
from django.template.loader import render_to_string
from django.utils.translation import gettext_lazy as _
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from recurrence.fields import RecurrenceField
from resource_hub.core.fields import (CustomManyToManyField,
                                      MultipleChoiceArrayField)
from resource_hub.core.models import (Actor, BaseAsset, BaseModel, Claim,
                                      Contract, ContractProcedure, Gallery,
                                      Location, Notification, Price)
from resource_hub.core.utils import get_valid_slug, language


class WorkshopContractProcedure(ContractProcedure):
    workshops = models.ManyToManyField(
        'Workshop',
        verbose_name=_('Workshop'),
    )

    @property
    def type_name(self):
        return _('Workshop contract procedure')

    @property
    def form_link(self):
        return reverse('control:workshops_contract_procedures_create')

    @property
    def edit_link(self):
        return reverse('control:workshops_contract_procedures_edit', kwargs={'pk': self.pk})


class Workshop(BaseAsset):

    # Fields
    contract_procedure = models.ForeignKey(
        ContractProcedure,
        on_delete=models.PROTECT,
        verbose_name=_('Contract procedure'),
    )
    workplaces = models.PositiveIntegerField(
        default=1,
    )
    bookable = models.BooleanField(
        default=True,
        verbose_name=_('Bookable?'),
    )
    owner = models.ForeignKey(
        Actor,
        on_delete=models.CASCADE,
        verbose_name=_('Owner'),
        help_text=_(
            'All available roles, be cautious when chosing a different role than your current.')
    )

    # Metadata
    class Meta:
        ordering = ['name']
        unique_together = ['name', 'location', ]

    # Methods
    def __str__(self):
        return '{}: {} ({})'.format(self.name, self.base_price, self.location.name)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.slug = get_valid_slug(
                self, self.name, Q(location=self.location))
        super(Workshop, self).save(*args, **kwargs)


class WorkshopPrice(Price):
    workshop_ptr = models.ForeignKey(
        Workshop,
        on_delete=models.PROTECT,
        related_name='workshop_price'
    )


class WorkshopBooking(BaseModel):
    # fields
    dtstart = models.DateTimeField(
        verbose_name=_('Start'),
    )
    dtend = models.DateTimeField(
        verbose_name=_('End'),

    )
    dtlast = models.DateTimeField()
    recurrences = RecurrenceField(
        null=False,
        blank=True,
        include_dtstart=True,
        verbose_name=_('Recurrences'),
    )
    workplaces = models.PositiveIntegerField(
        default=1,
    )
    workshops = CustomManyToManyField(
        Workshop,
        verbose_name=_('Workshop'),
    )
    # Methods

    @classmethod
    def build_occurrences(cls, dates: list, dtstart, dtend) -> dict:
        result = {
            'occurrences': [],
            'dtlast': None
        }
        for date in dates:
            # get last occurrence and apply times to dates

            occurrence_start = datetime.combine(
                date.date(), dtstart.time(), dtstart.tzinfo)
            occurrence_end = datetime.combine(
                date.date(), dtend.time(), dtend.tzinfo)
            result['occurrences'].append(
                (occurrence_start, occurrence_end)
            )
            result['dtlast'] = occurrence_end

        return result

    @property
    def occurrences(self) -> list:
        return self.build_occurrences(self.recurrences.occurrences(), self.dtstart, self.dtend)['occurrences']


class WorkshopEquipment(models.Model):
    # fields
    name = models.CharField(
        max_length=128,
        unique=True,
        verbose_name=_('Name'),
    )
    workshop = models.ForeignKey(
        Workshop,
        on_delete=models.PROTECT,
        verbose_name=_('Workshop'),
        related_name='equipment',
    )
    thumbnail_original = models.ImageField(
        verbose_name=_('Thumbnail'),

    )
    thumbnail = ImageSpecField(
        source='thumbnail_original',
        processors=[ResizeToFill(200, 200)],
        format='JPEG',
        options={'quality': 70},
    )
    thumbnail_large = ImageSpecField(
        source='thumbnail_original',
        processors=[ResizeToFill(400, 400)],
        format='JPEG',
        options={'quality': 90},
    )
    price = models.ForeignKey(
        Price,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        verbose_name=_('Price'),
    )
    quantity = models.IntegerField(
        verbose_name=_('Quantity'),
    )

    # methods
    def __str__(self):
        return '{}@{} ({})'.format(self.name, self.workshop.name, self.price)


class WorkshopEquipmentPrice(Price):
    equipment_ptr = models.ForeignKey(
        WorkshopEquipment,
        on_delete=models.PROTECT,
        related_name='equipment_price'
    )


class EquipmentBooking(BaseModel):
    # fields
    contract = models.ForeignKey(
        'WorkshopContract',
        on_delete=models.PROTECT,
        verbose_name=_('Contract'),
        related_name='equipment_bookings',
    )
    equipment = models.ForeignKey(
        'WorkshopEquipment',
        on_delete=models.PROTECT,
        verbose_name=_('WorkshopEquipment'),
        related_name='equipment_bookings',
    )
    quantity = models.PositiveIntegerField(
        default=1,
        verbose_name=_('Quantity'),
    )


class WorkshopContract(Contract):
    booking = models.OneToOneField(
        WorkshopBooking,
        on_delete=models.PROTECT,
        verbose_name=_('Event'),
    )
    equipment = CustomManyToManyField(
        WorkshopEquipment,
        blank=True,
        through='EquipmentBooking',
        verbose_name=_('WorkshopEquipment'),
        help_text=_('Services or additional equipment for the workshop'),

    )

    # attributes
    @property
    def verbose_name(self):
        return _('Workshop booking')

    @property
    def overview(self):
        return render_to_string(
            'workshops/_contract_overview.html',
            context={
                'contract': self,
            }
        )

    # methods
    def claim_factory(self, **kwargs):
        super(WorkshopContract, self).claim_factory(**kwargs)
        occurrences = kwargs.get('occurrences', None)
        if not occurrences:
            raise ValueError('no occurrences passed')
        net_total = 0
        for i in range(1, self.booking.workplaces + 1):
            for workshop in self.booking.workshops.all():
                for occurrence in occurrences:
                    start = occurrence[0]
                    end = occurrence[1]
                    delta = ((end - start).total_seconds())/3600
                    claim = Claim.build(
                        contract=self,
                        item=_('%(workplace)s (Workplace %(no)d)') % {
                            'workplace': workshop.name,
                            'no': i,
                        },
                        quantity=delta,
                        unit='h',
                        price=workshop.base_price,
                        start=start,
                        end=end,
                    )
                    net_total += claim.net

        for booking in self.equipment_bookings.all():
            for occurrence in occurrences:
                equipment = booking.equipment
                Claim.build(
                    contract=self,
                    item='{}@{}'.format(
                        equipment.name,
                        equipment.workshop.name,
                    ),
                    quantity=booking.quantity,
                    unit='u',
                    price=equipment.price,
                    start=occurrence[0],
                    end=occurrence[1],
                )

        self.create_fee_claims(
            net_total, workshop.base_price.currency, start, end)

    # state setters

    def purge(self):
        super(WorkshopContract, self).purge()
        self.booking.soft_delete()

    def set_waiting(self, request):
        super(WorkshopContract, self).set_waiting(request)
        with language(self.creditor.language):
            Notification.build(
                type_=Notification.TYPE.CONTRACT,
                sender=self.debitor,
                recipient=self.creditor,
                header=_('%(debitor)s created Booking') % {
                    'debitor': self.debitor,
                },
                link=reverse('control:finance_contracts_manage_details',
                             kwargs={'pk': self.pk}),
                level=Notification.LEVEL.MEDIUM,
                message='',
                target=self,
            )

    def set_terminated(self, initiator):
        super(WorkshopContract, self).set_terminated(initiator)
        self.booking.soft_delete()

src/resource_hub/templates/__base.html
{% load static %}
{% load sekizai_tags %}
{% load i18n %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">

<head>
    {% block meta_tags %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock %}
<title>{% if request.META.HTTP_HOST == 'egons-verleih.de' %}Egons Verleih{% else %}Resource Hub{% endif %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />

    {% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static "semantic/semantic.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
    <script src="{% static "jquery/jquery.min.js" %}"></script>
    <script src="{% static "js/utils.js" %}"></script>
    {% endblock %}
    {% block extra_head %}
    {% endblock %}
    {%  render_block 'extra_head' %}
</head>

<body>
    <header class="nav">
        {% include "_navigation_bar.html" %}
    </header>
    {% include "_sidebar.html" %}
    {% block body %}
    {% endblock %}
    <main id="main" class="pusher">
        {% include '_scroll-button.html' %}
        {% block main %}
        {% endblock %}
        {% render_block 'main' %}
    </main>
    {% render_block 'after-main' %}
    <footer class="pusher">
        {% block footer %}
        {% endblock %}
        {% block javascript %}
        <script src="{% static "semantic/semantic.min.js" %}"></script>
        <script src="{% static "js/scroll-button.js" %}"></script>
        <script src="{% static "js/navigation.js" %}"></script>
        {% endblock %}
        {% render_block 'prio-js' %}
        {% block scripts %}
        {% endblock %}
        {%  render_block 'js' %}
    </footer>
</body>

</html>

src/resource_hub/templates/__mail.html
{% load i18n %}

<p>
    {% block content %}
    {% endblock %}
</p>
<p>
    {% blocktrans %}
    With regards,
    {% endblocktrans %}
    <br />
    <b>Resource Hub Team</b>
</p>

src/resource_hub/templates/_calendar.html
{% load i18n %}
{% load static %}
{% load sekizai_tags %}


{% addtoblock 'extra_head' %}
<link href="{% static 'fullcalendar/main.min.css' %}" rel="stylesheet">
<link href="{% static 'fullcalendar/daygrid/main.min.css' %}" rel="stylesheet">
<link href="{% static 'fullcalendar/timegrid/main.min.css' %}" rel="stylesheet">
<link href="{% static 'fullcalendar/list/main.min.css' %}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'datetimepicker/jquery.datetimepicker.css' %}" />

<script src="{% static 'fullcalendar/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/daygrid/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/timegrid/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/list/main.min.js' %}"></script>
<script src="{% static 'fullcalendar/interaction/main.min.js' %}"></script>

<script>
    var calendar = null;
    document.addEventListener('DOMContentLoaded', function () {
        var locale = '{{ lang }}';
        var calendarEl = document.getElementById('calendar');

        calendar = new FullCalendar.Calendar(calendarEl, {
            events: function (info, successCallback, failureCallback) {
                $.get("{{ event_url }}", {
                    start: info.startStr,
                    end: info.endStr
                }).done(function (data) {
                    successCallback(
                        data.results
                    )
                })
            },
            plugins: ['list', 'dayGrid', 'interaction'],
            locale: locale,
            selectable: true,
            unselectAuto: false,
            unselectCancel: 'fc-button ',
            select: function (selectionInfo) {
                dtPickerStart.datetimepicker({ value: selectionInfo.start })
                dtPickerEnd.datetimepicker({ value: selectionInfo.end })
            },
            defaultView: 'dayGridMonth',
            contentHeight: 'auto',
            header: { left: 'title', center: '', right: 'dayGridMonth,listWeek prev,next' },
            buttonText: {
                'dayGridMonth': "{% trans 'month' %}",
                'listWeek': "{% trans 'week' %}"

            },
        });

        calendar.render();
    });
</script>
{% endaddtoblock %}


<div class="calendar" id='calendar'></div>
{% if ics_url %}
<div class="section-container">
    <div class="ui left action input">
        <button class="ui teal left labeled icon copy button" data-content="{% trans 'Link copied!' %}" data-tooltip="
{% trans 'Copy link' %}" onclick="copy(this)">
            {% trans 'Subscribe' %}
            <i class="rss icon"></i>
        </button>
        <input id="value-to-copy" type="text" value="{{ request.scheme }}://{{ request.get_host }}">
    </div>
    <div>
        <span class="help">{% trans 'Add this iCal-feed to your calendar app (Google calendar, Nextcloud etc.)' %}
        </span>
    </div>
</div>
{% endif %}

{% addtoblock 'js' %}
<script src="{% static 'datetimepicker/build/jquery.datetimepicker.full.min.js' %}"></script>
<script>
    function setEnd(currentDateTime) {
        dtPickerEnd.datetimepicker({
            minDate: currentDateTime,
            defaultTime: currentDateTime,
            defaultDate: currentDateTime
        })
    }
    var format = "{{ format }}";
    var timepicker = format == 'Y-m-d' ? false : true;
    var locale = "{{ lang }}";
    var selectedStart = null;
    var selectedEnd = null;
    jQuery.datetimepicker.setLocale(locale);
    var dtPickerStart = $('#id_dtstart').datetimepicker({
        onChangeDateTime: setEnd,
        step: 30,
        format: format,
        mask: true,
        timepicker: timepicker,
        onSelectDate: function (currentDateTime) {
            selectedStart = currentDateTime;
            calendar.select(selectedStart);
        }

    });
    var dtPickerEnd = $('#id_dtend').datetimepicker({
        step: 30,
        format: format,
        mask: true,
        timepicker: timepicker,
        onSelectDate: function (currentDateTime) {
            selectedEnd = currentDateTime;
            calendar.select(selectedStart, selectedEnd);
        }
    });
</script>
{% endaddtoblock %}

src/resource_hub/templates/_editable_table.html
{% load i18n %}
{% load sekizai_tags %}

{% addtoblock 'after-main' %}
<nav id="save-bar" class="hidden saving navigation-bar">
    <div></div>
    <div class="right">
        <button id="cancel" class="ui button">
            {% trans 'Cancel' %}
        </button>
        <button id="save" class="ui green right labeled icon button">
            {% trans 'Save' %}
            <i class="save icon"></i>
        </button>
    </div>
</nav>
{% endaddtoblock %}
{% addtoblock 'js' %}
<script>
    $(document).ready(function () {
        var updates = {};
        var submit = false;

        window.addEventListener("beforeunload", function (e) {
            if (jQuery.isEmptyObject(updates) || submit) {
                return;
            }
            var confirmationMessage = "{% trans 'There are unsaved changes. Do you want to continue?' %}";

            (e || window.event).returnValue = confirmationMessage; //Gecko + IE
            return confirmationMessage; //Gecko + Webkit, Safari, Chrome etc.
        });
        $('.row').on('input', function (e) {
            e.preventDefault();
            //select row and table
            var row = $(this);
            console.log(row)
            var pk = row.attr('pk');

            var values = {};
            row.find('.input').each(function (i, element) {
                values[element.name] = element.value;
            })
            //save updated values to object
            updates[pk] = values;

            //display save button
            if ($('#save-bar').hasClass('hidden')) {
                $('#save-bar').removeClass('hidden');
            }
        });

        $('#save').on('click', function (e) {
            e.preventDefault();
            submit = true;
            var csrftoken = getCookie('csrftoken');
            $.ajax({
                url: "{{ url }}",
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                data: JSON.stringify(updates),
                headers: { 'X-CSRFToken': csrftoken },
            }).fail(function (data) {
                alert(data.responseJSON)
            }).done(function (data) {
                window.location.reload(true);
            });
        });

        $('#cancel').on('click', function (e) {
            e.preventDefault();
            submit = true;
            window.location.reload(true);
        });
    });
</script>
{% endaddtoblock %}

src/resource_hub/templates/_info.html
<div class="ui segment">
    <p class="">
        <i class="info circle icon"></i>
        {{ text }}
    </p>
</div>

src/resource_hub/templates/_map.html
{% load sekizai_tags %}
{% load static %}
{% load l10n %}
{% load i18n %}

<div id="map" class="map">

</div>

{% addtoblock 'js' %}
<link rel="stylesheet" href="{% static 'leaflet/leaflet.css' %}">
<script src="{% static 'leaflet/leaflet.js' %}"></script>
<script src="{% static 'bouncemarker/bouncemarker.js' %}"></script>
{% if location %}
{% localize off %}
<script>
    var position = [parseFloat('{{ location.latitude }}'), parseFloat('{{ location.longitude }}')] 
</script>
{% endlocalize %}
{% else %}
<script>
    var position = [52.3882397, 9.722311];
</script>
{% endif %}
<script>
    if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
        var url = 'https://api.mapbox.com/styles/v1/mark-weyde/ck7qf0hz80iq31ipm6dfvk4so/tiles/256/{z}/{x}/{y}@2x?access_token={accessToken}'
    } else {
        var url = 'https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}';
    }
    var map = L.map('map').setView(position, 11.5);
    L.tileLayer(url, {
        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
        maxZoom: 20,
        tileSize: 512,
        zoomOffset: -1,
        id: 'mapbox/streets-v11',
        accessToken: '{{ MAP_API_TOKEN }}'
    }).addTo(map);

    var marker = L.icon({
        iconUrl: '{% static "marker.png" %}',
        iconSize: [23, 40],
        iconAnchor: [11.5, 39],
        popupAnchor: [0, -40]
    });
</script>
{% if location %}
<script id="pop-up-template" type="text/tempate">
    <h5>%name%</h5>
    <p><i class="map marker alternate icon"></i>%address_string%</p>
    <a class="ui positive button" href="%location_link%">{% trans 'Details' %}</a>
</script>
<script>
    var popup_template = document.getElementById("pop-up-template").innerHTML;
    var popup = popup_template
        .replace(/%name%/g, '{{ location.name }}')
        .replace(/%address_string%/g, '{{ location.address }}')
        .replace(/%location_link%/g, '{% url "core:locations_profile" slug=location.slug %}');
    L.marker(position, {
        bounceOnAdd: true,
        bounceOnAddOptions: { duration: 500, height: 70 },
        icon: marker,
        title: '{{ location.name }}',
        clickable: true,
    }).bindPopup(popup).addTo(map).openPopup();
</script>
{% endif %}
{% endaddtoblock %}

src/resource_hub/templates/_save_button.html
{% load i18n %}
<button class="ui positive right labeled icon button" type="submit">
    {% trans 'save' %}
    <i class="save icon"></i>
</button>

src/resource_hub/templates/_support-button.html
{% load i18n %}
<a id="support" title="Get support" class="ui small positive left labeled icon button"
    href="{% url 'core:report_bug' %}">
    {% trans 'report' %}
    <i class="bug icon"></i>
</a>